#!/bin/env python3

import sys
from termcolor import colored

def solve(inp, part2=False):
    part = '1' if not part2 else '2'
    import subprocess
    cp = subprocess.run(["./main.py", part],
                        input=bytes(inp, 'utf-8'),
                        capture_output=True)
    return cp.stdout.decode('utf-8').strip()

def run_test(tname, inp, exp, part2):
    sol = solve(inp, part2)
    if str(sol) != exp:
        print(colored(f"Wrong on {tname}!", 'red'))
        print(f"Expected {exp}")
        print(f"Got {sol}")
    else:
        print(colored(f"Correct on {tname}!", 'green'))
        print(f"Got {sol}")

def run_tests(part2):
    import glob
    tests = list(glob.glob("test*.in"))
    for in_fn in tests:
        inp = open(in_fn, 'r').read().strip()
        tname = in_fn.split('.')[0]
        out_fn = f'{tname}.{2 if part2 else 1}.out'
        try:
            exp = open(out_fn, 'r').read().strip()
        except:
            print(f"No solution for {tname}, part {2 if part2 else 1}")
            continue
        run_test(tname, inp, exp, part2)

def main(*argv):
    run_tests('2' in argv[0])

if __name__ == "__main__":
    main(sys.argv)
